USB_VID = 0x303a
USB_PID = 0x8154
USB_PRODUCT = "T-QT"
USB_MANUFACTURER = "LILYGO"

IDF_TARGET = esp32s3

CIRCUITPY_ESP_FLASH_MODE = dio
CIRCUITPY_ESP_FLASH_FREQ = 40m
CIRCUITPY_ESP_FLASH_SIZE = 4MB

OPTIMIZATION_FLAGS = -Os
CIRCUITPY_ESPCAMERA = 0
