USB_VID = 0x303a
USB_PID = 0x82C2
USB_PRODUCT = "T-Dongle S3"
USB_MANUFACTURER = "LILYGO"

IDF_TARGET = esp32s3

CIRCUITPY_ESP_FLASH_SIZE = 16MB
CIRCUITPY_ESP_FLASH_MODE = qio
CIRCUITPY_ESP_FLASH_FREQ = 80m

# Few pins.
CIRCUITPY_ESPCAMERA = 0
