# Configuration for nrf5340bsim simulated board
# Mirror settings from native_sim.conf for compatibility

CONFIG_GPIO=y

# Enable Bluetooth stack - bsim is for BT simulation
CONFIG_BT_HCI=y
CONFIG_BT_HCI_VS=y

# Override Kconfig default
CONFIG_BT_BUF_CMD_TX_COUNT=2

# Ensure the network core image starts when using native simulator
CONFIG_NATIVE_SIMULATOR_AUTOSTART_MCU=y

CONFIG_TRACING=y
CONFIG_TRACING_PERFETTO=y
CONFIG_TRACING_SYNC=y
CONFIG_TRACING_BACKEND_POSIX=y
CONFIG_TRACING_GPIO=y
