# No Bluetooth hardware on native_sim
CONFIG_BT=n

CONFIG_EMUL=y
CONFIG_GPIO=y
CONFIG_NATIVE_SIM_SLOWDOWN_TO_REAL_TIME=n

# So we can test safe mode
CONFIG_NATIVE_SIM_REBOOT=y

CONFIG_TRACING=y
CONFIG_TRACING_PERFETTO=y
CONFIG_TRACING_SYNC=y
CONFIG_TRACING_BACKEND_POSIX=y
CONFIG_TRACING_GPIO=y

# I2C emulation for testing
CONFIG_I2C_EMUL=y

# Display emulation for display/terminal golden tests.
CONFIG_DISPLAY=y
CONFIG_SDL_DISPLAY=y

# EEPROM emulation for testing
CONFIG_EEPROM=y
CONFIG_EEPROM_AT24=y
CONFIG_EEPROM_AT2X_EMUL=y

# I2S SDL emulation for audio testing
CONFIG_I2S_SDL=y

CONFIG_NETWORKING=y
CONFIG_NET_IPV4=y
CONFIG_NET_TCP=y
CONFIG_NET_SOCKETS=y
CONFIG_ETH_NATIVE_TAP=n
CONFIG_NET_DRIVERS=y
CONFIG_NET_SOCKETS_OFFLOAD=y
CONFIG_NET_NATIVE_OFFLOADED_SOCKETS=y
CONFIG_HEAP_MEM_POOL_SIZE=1024

CONFIG_NET_LOG=y

CONFIG_MBEDTLS=y
CONFIG_PSA_WANT_ALG_SHA_1=y
CONFIG_PSA_WANT_ALG_SHA_256=y
