manifest:
  group-filter:
    - +babblesim
  projects:
    - name: nrf_hw_models
      url: https://github.com/tannewt/ext_nRF_hw_models
      revision: c2927847bdf2ee0af9c5459f4155c67f39f6837a
      path: modules/bsim_hw_models/nrf_hw_models
    - name: zephyr
      url: https://github.com/adafruit/zephyr
      revision: 63f054c88ee158a3d755bd59a26ef874f650efa2
      clone-depth: 100
      import: true
