manifest:
  group-filter:
    - +babblesim
  projects:
    - name: nrf_hw_models
      url: https://github.com/tannewt/ext_nRF_hw_models
      revision: 41cb69cd08848cc31e91ed62d01d397511981919
      path: modules/bsim_hw_models/nrf_hw_models
    - name: zephyr
      url: https://github.com/adafruit/zephyr
      revision: 499310df6e4da5ca54165c4b4c4c714771acb84c
      clone-depth: 100
      import: true
