USB_VID = 0x239A
USB_PID = 0x804A
USB_PRODUCT = "Hallowing M4 Express"
USB_MANUFACTURER = "Adafruit Industries LLC"

CHIP_VARIANT = SAMD51J19A
CHIP_FAMILY = samd51

QSPI_FLASH_FILESYSTEM = 1
EXTERNAL_FLASH_DEVICES = "GD25Q64C,W25Q64JVxQ"
LONGINT_IMPL = MPZ

CIRCUITPY_AESIO = 0
CIRCUITPY_CODEOP = 0
CIRCUITPY_EPAPERDISPLAY = 0
CIRCUITPY_FLOPPYIO = 0
CIRCUITPY_I2CDISPLAYBUS = 0
CIRCUITPY_I2CTARGET = 0
CIRCUITPY_PARALLELDISPLAYBUS = 0
CIRCUITPY_RGBMATRIX = 0
CIRCUITPY_SHARPDISPLAY = 0
CIRCUITPY_SPITARGET = 0
