USB_VID = 0x239A
USB_PID = 0x814E
USB_PRODUCT = "Metro RP2350"
USB_MANUFACTURER = "Adafruit"

CHIP_VARIANT = RP2350
CHIP_PACKAGE = B
CHIP_FAMILY = rp2

EXTERNAL_FLASH_DEVICES = "W25Q128JVxQ"

CIRCUITPY_SDIOIO = 1

CIRCUITPY_PICOGAME = 1
CIRCUITPY_PICOGAME_FRAMEBUFFER = 1
CIRCUITPY_PICOGAME_FAST_DISPLAY = 1
