// iobroker: dynamic peripheral allocation and runtime pin routing.
//
// This file is part of the CircuitPython project: https://circuitpython.org
//
// SPDX-FileCopyrightText: Copyright (c) 2025 Adafruit Industries LLC
//
// SPDX-License-Identifier: MIT

// Allocate a free bus instance (I2C, SPI, UART) enabled in the devicetree,
// route it to the requested pins at runtime and hand the Zephyr device to the
// caller. Per-board tables of allocatable instances are provided by the
// application (the CircuitPython build generates them from the board's
// devicetree; see modules/iobroker/README.md for the contract).
//
// Runtime routing works on nRF SoCs because their pin control encoding is a
// simple bit-packed value (see zephyr/dt-bindings/pinctrl/nrf-pinctrl.h and
// soc/nordic/common/pinctrl_soc.h) that can be computed at runtime, and any
// peripheral function can be routed to (almost) any pin via PSEL.

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include <zephyr/device.h>
#include <zephyr/drivers/gpio.h>

// Runtime bus routing lets the module re-route a bus instance's pins at
// runtime. It is available when Zephyr is built with dynamic pinctrl states and
// device de-init support. Without it the bus allocate/release functions report
// -ENOSYS and the bus instance tables are not used.
#if defined(CONFIG_PINCTRL_NRF) && defined(CONFIG_PINCTRL_DYNAMIC) && \
    defined(CONFIG_DEVICE_DEINIT_SUPPORT)
#define IOBROKER_ROUTING 1
#else
#define IOBROKER_ROUTING 0
#endif

// Signals needed by the widest bus (UART with tx/rx/rts/cts).
#define IOBROKER_MAX_PINS 4

// Package pin that leaves a signal disconnected (only valid for optional
// signals such as UART rts/cts).
#define IOBROKER_NO_PIN ((package_pin_t)0xffff)

// A physical pin of the SoC's package, numbered the way the SoC datasheet
// numbers its package pins (1..N for QFN-style packages; BGA-style packages
// use the datasheet's sequential numbering of the balls). Translating a pin
// name from a schematic or board layout to a package pin is a board concern;
// the module only knows the package pin -> SoC pad mapping below.
typedef uint16_t package_pin_t;

// Wrap a datasheet package pin number into a package_pin_t.
#define PACKAGE_PIN(number) ((package_pin_t)(number))

// One entry of the package pin map: a physical package pin and the SoC pad
// it is bonded to (gpio port index * 32 + pin within the port; the same
// numbering that CircuitPython's Pin objects and the GPIO controller table
// below use). Package pins that are not bonded to a GPIO (power, analog
// only, ...) are omitted; requesting one fails with -EINVAL.
//
// The map is generated by the module build from the selected IOBROKER_PACKAGE
// choice (see packages/), or as an empty map when no package applies to the
// SoC. With an empty map every package pin lookup fails with -EINVAL.
typedef struct {
    package_pin_t package_pin;
    uint16_t soc_pad;
} iobroker_package_pin_t;

extern const iobroker_package_pin_t iobroker_package_pins[];
extern const size_t iobroker_package_pin_count;

// GPIO controller table: the board lists every GPIO controller together with
// its hardware port index, which defines the global pin numbering
// (index * 32 + pin). Generated into board.c; boards without GPIO
// controllers generate an empty table, so lookups return -EINVAL.
extern const struct device *const iobroker_gpio_port_devices[];
extern const uint8_t iobroker_gpio_port_indexes[];
extern const size_t iobroker_gpio_port_count;

// Resolve a global pin number to its GPIO controller device and the pin
// number within that controller (the two values Zephyr's GPIO API takes).
// Returns 0, or -EINVAL when no controller covers the number.
int iobroker_gpio_split(uint16_t number, const struct device **port_out,
    gpio_pin_t *pin_out);

// Map a GPIO controller's hardware port index and the pin number within it
// (the two halves of the global pin numbering: index * 32 + pin) to the
// package pin the pad is bonded to. The inverse of the package pin map's
// soc_pad column. Returns 0, or -EINVAL when the pad has no entry in the
// package pin map.
int iobroker_gpio_package_pin(uint8_t port, gpio_pin_t pin,
    package_pin_t *package_pin_out);

#if defined(CONFIG_PINCTRL_NRF)

#include <zephyr/drivers/pinctrl.h>

// Description of one allocatable bus instance. Filled in by the board tables.
typedef struct {
    const struct device *dev;
    // Pin control configuration of the device. Mutable because
    // CONFIG_PINCTRL_DYNAMIC moves these to RAM so that states can be
    // swapped at runtime.
    struct pinctrl_dev_config *pcfg;
    // Pin control entries of the devicetree "default" state, or NULL when
    // the instance was enabled with disconnected pins so that it can be
    // routed dynamically to any pin.
    const pinctrl_soc_pin_t *dt_psels;
    uint8_t dt_psel_count;
} iobroker_instance_t;

// Runtime bookkeeping for one allocatable bus instance. The arrays live for
// the life of the firmware because Zephyr's pinctrl API keeps pointers to
// them inside the device's pinctrl_dev_config.
typedef struct {
    pinctrl_soc_pin_t default_pins[IOBROKER_MAX_PINS];
    pinctrl_soc_pin_t sleep_pins[IOBROKER_MAX_PINS];
    struct pinctrl_state states[2];
    bool in_use;
    // True when the instance's states were swapped for runtime-built entries.
    bool routed;
    // Package pins the current allocation claims (copies of the request).
    // Used by iobroker_pin_in_use(); empty while the instance is free.
    package_pin_t pins[IOBROKER_MAX_PINS];
    uint8_t pin_count;
} iobroker_state_t;

// Generated board tables, emitted by the board's generated board.c whenever
// the nRF pinctrl driver is built. They are used only when runtime routing is
// available (IOBROKER_ROUTING); boards without it still define them.
extern const iobroker_instance_t iobroker_i2c_buses[];
extern const size_t iobroker_i2c_bus_count;
extern iobroker_state_t iobroker_i2c_bus_states[];

extern const iobroker_instance_t iobroker_spi_buses[];
extern const size_t iobroker_spi_bus_count;
extern iobroker_state_t iobroker_spi_bus_states[];

extern const iobroker_instance_t iobroker_uart_buses[];
extern const size_t iobroker_uart_bus_count;
extern iobroker_state_t iobroker_uart_bus_states[];

// SoC pads owned by fixed peripherals (console UART, flash instance, I2S,
// ...): the pads their devicetree pinctrl default state drives at boot.
// iobroker_pin_in_use() reports these as always busy so that allocate()
// rejects requests for them with -EBUSY.
extern const uint16_t iobroker_reserved_pads[];
extern const size_t iobroker_reserved_pads_count;

#endif // CONFIG_PINCTRL_NRF

// The functions below return 0 on success and set *dev_out to the Zephyr
// device of an allocated instance. A negative errno is returned on failure:
//   -ENODEV: no compatible instance is free
//   -ENOSYS: dynamic pin routing is unsupported on this SoC
//   -EBUSY: a requested pin is already claimed by an allocated instance
//   -EINVAL/-EIO: a pin or routing operation failed
// Optional signals may be disconnected (IOBROKER_NO_PIN). Every allocate
// call must be paired with iobroker_release().
int iobroker_i2c_allocate(package_pin_t sda, package_pin_t scl,
    const struct device **dev_out);
int iobroker_spi_allocate(package_pin_t clock, package_pin_t mosi,
    package_pin_t miso, const struct device **dev_out);
int iobroker_uart_allocate(package_pin_t tx, package_pin_t rx,
    package_pin_t rts, package_pin_t cts, const struct device **dev_out);

// Returns true when the package pin is currently claimed by an allocated bus
// instance, a GPIO allocation, or a fixed peripheral (console UART, flash
// instance, ... whose pads are listed in iobroker_reserved_pads). Call this
// before allocate() to find out which requested pin is already in use.
// Disconnected signals (IOBROKER_NO_PIN) and package pins with no SoC pad are
// never in use.
bool iobroker_pin_in_use(package_pin_t pin);

// Allocate a package pin for plain GPIO use. The module only claims it: while
// held, bus allocate() calls and further GPIO allocations fail with -EBUSY.
// The pin is resolved through the package pin map, and both values Zephyr's
// GPIO API needs are returned: *port_out receives the GPIO controller device
// and *pin_out the pin number within it, so that the caller can configure the
// pad itself (gpio_pin_configure()). Returns 0, or a negative errno:
//   -EINVAL: pin is disconnected (IOBROKER_NO_PIN) or has no entry in the
//            package pin map
//   -EBUSY: the pin is already claimed
//   -ENOMEM: the GPIO claim registry is full
int iobroker_gpio_allocate(package_pin_t pin,
    const struct device **port_out, gpio_pin_t *pin_out);

// Release a GPIO claim made with iobroker_gpio_allocate() and return the pad
// to a quiescent state: disconnected from any peripheral routing, input
// buffer and driver off, no pulls (a plain input on SoCs without
// GPIO_DISCONNECTED support). Pass the device and pin number that the
// allocate call returned. Returns true when a claim was held.
bool iobroker_gpio_release(const struct device *port, gpio_pin_t number);

// Release an instance previously returned by one of the allocate functions.
// Returns true when the instance had been dynamically routed, in which case
// the caller is responsible for resetting the pins it had routed to it. The
// device is de-initialized on release, so it is left uninitialized; the
// caller initializes it again when it allocates the instance next.
bool iobroker_release(const struct device *dev);
