USB_VID = 0x1209
USB_PID = 0xBAB0
USB_PRODUCT = "Bast WiFi"
USB_MANUFACTURER = "ElectronicCats"

IDF_TARGET = esp32s2

CIRCUITPY_ESP_FLASH_MODE = qio
CIRCUITPY_ESP_FLASH_FREQ = 80m
CIRCUITPY_ESP_FLASH_SIZE = 4MB
