USB_VID = 0x2E8A
USB_PID = 0x0005
USB_PRODUCT = "W55RP20-EVB-Pico"
USB_MANUFACTURER = "WIZnet"

CHIP_VARIANT = RP2040
CHIP_FAMILY = rp2

EXTERNAL_FLASH_DEVICES = "PY25Q16HB"

CIRCUITPY_WIZNET = 1
CIRCUITPY__EVE = 1
CIRCUITPY_SSL = 1
CIRCUITPY_USB_HOST = 0

OPTIMIZATION_FLAGS = -O2
