# Configuration for nrf54lm20bsim simulated board

CONFIG_GPIO=y

# Enable Bluetooth stack - bsim is for BT simulation
CONFIG_BT_HCI=y
CONFIG_BT_HCI_VS=y

# Match nrf54lm20dk hardware: support dynamic TX power control
CONFIG_BT_CTLR_TX_PWR_DYNAMIC_CONTROL=y

# Override Kconfig default
CONFIG_BT_BUF_CMD_TX_COUNT=2

CONFIG_TRACING=y
CONFIG_TRACING_PERFETTO=y
CONFIG_TRACING_SYNC=y
CONFIG_TRACING_BACKEND_POSIX=y
CONFIG_TRACING_GPIO=y
