CONFIG_FLASH_MSPI_NOR_LAYOUT_PAGE_SIZE=4096

# BLE overflows flash on this board.
CONFIG_BT=n

# Reduce flash usage for this board.
CONFIG_LOG=y
CONFIG_LOG_MAX_LEVEL=2
CONFIG_ASSERT=n
CONFIG_FRAME_POINTER=n
CONFIG_HW_STACK_PROTECTION=n
