USB_VID = 0x2886
USB_PID = 0x0300

USB_PRODUCT = "Seeed Xiao ESP32-S3 Trmnl DIY Kit"
USB_MANUFACTURER = "Seeed Studio"

IDF_TARGET = esp32s3

CIRCUITPY_ESP_FLASH_MODE = qio
CIRCUITPY_ESP_FLASH_SIZE = 16MB
CIRCUITPY_ESP_FLASH_FREQ = 80m

CIRCUITPY_ESP_PSRAM_MODE = opi
CIRCUITPY_ESP_PSRAM_SIZE = 8MB
CIRCUITPY_ESP_PSRAM_FREQ = 80m

CIRCUITPY_FREQUENCYIO = 0
CIRCUITPY_RAINBOWIO = 0
CIRCUITPY__EVE = 0
CIRCUITPY_PS2IO = 0
CIRCUITPY_CANIO = 0
CIRCUITPY_MAX3421E = 0
CIRCUITPY_ESPCAMERA = 0
CIRCUITPY_PARALLELDISPLAYBUS = 0
CIRCUITPY_COUNTIO = 0
CIRCUITPY_NEOPIXEL_WRITE = 0
CIRCUITPY_ROTARYIO = 0

CIRCUITPY_AUDIOCORE = 0
CIRCUITPY_AUDIOBUSIO = 0
CIRCUITPY_AUDIOBUSIO_PDMIN = 0
CIRCUITPY_AUDIOI2SIN = 0
