USB_PRODUCT = "Waveshare ESP32-C5 LCD 1.47"
USB_MANUFACTURER = "Waveshare"

CIRCUITPY_CREATOR_ID = 0x000C303A
CIRCUITPY_CREATION_ID = 0x00C50002

IDF_TARGET = esp32c5

CIRCUITPY_ESP_FLASH_MODE = qio
CIRCUITPY_ESP_FLASH_FREQ = 80m
CIRCUITPY_ESP_FLASH_SIZE = 4MB

CIRCUITPY_NEOPIXEL_WRITE = 1
CIRCUITPY_BUSDISPLAY = 1
CIRCUITPY_FOURWIRE = 1
CIRCUITPY_4MB_FLASH_LARGE_USER_FS_LAYOUT = 1
